export type {
  ContactInfo,
  Education,
  EmailUrl,
  Experience,
  ExperienceKind,
  ExternalUrl,
  LocalizedStringList,
  LocalizedText,
  PersonalInfo,
  PortfolioLocale,
  Project,
  ProjectRepository,
  ProjectStatus,
  ProjectVisual,
  SkillCategory,
  SocialIcon,
  SocialLink,
} from "./portfolio";
