export type {
  AboutHighlight,
  AboutHighlightIcon,
  AboutHighlightVariant,
  ContactInfo,
  CoreTechnology,
  CoreTechnologyVisual,
  Education,
  EmailUrl,
  Experience,
  ExperienceKind,
  ExperienceVisual,
  ExternalUrl,
  LocalizedStringList,
  LocalizedText,
  PersonalInfo,
  PortfolioLocale,
  Project,
  ProjectRepository,
  ProjectStatus,
  ProjectVisual,
  SkillCategory,
  SkillCategoryIcon,
  SocialIcon,
  SocialLink,
} from "./portfolio";
